/*
 * GPIO and IRQ definitions for HTC Athena PDA phones
 *
  * Copyright (c) 2009 Olivier Grisoni
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 *
 */

#ifndef _HTCATHENA_H_
#define _HTCATHENA_H_

#include <mach/irqs.h>

/*
 * 5 Chip Selects
 *
 * CS0 IPL
 * CS1 W2284
 * CS2 CPLD1 & CPLD2
 * CS3 Epson
 * CS4 DPRAM
 *
 *
 */


#define HTCATHENA_W2284_BASE_PHYS	PXA_CS1_PHYS
#define HTCATHENA_W2284_CTRL_PHYS	(PXA_CS1_PHYS+0x00010000)
#define HTCATHENA_W2284_MMC_PHYS	(PXA_CS1_PHYS+0x00200000)

#define HTCATHENA_CPLD1_BASE		PXA_CS2_PHYS

#define HTCATHENA_EGPIO_CPLD2_BASE_0	(PXA_CS2_PHYS+0x01000000)
#define HTCATHENA_EGPIO_CPLD2_BASE_1	(PXA_CS2_PHYS+0x02000000)
#define HTCATHENA_DPRAM_BASE		PXA_CS4_PHYS



/*
 * CPLD EGPIOs
 */
#define NR_BUILTIN_GPIO PXA_NR_BUILTIN_GPIO

/*	NR_BUILTIN_GPIO + x	*/

#define CPLD1_EGPIO_BASE PXA_NR_BUILTIN_GPIO
#define CPLD2_EGPIO_BASE (PXA_NR_BUILTIN_GPIO + 64)
#define GPIO_BASE_MASK 0xff

/*
 * PXA 120 GPIOs
 */

#define GPIO0_HTCATHENA_KEY_POWER		0
#define GPIO1_HTCATHENA_ISP1582_INT		1
#define GPIO2_HTCATHENA_RESERVED		2
#define GPIO3_HTCATHENA_TBD			3
#define GPIO4_HTCATHENA_TBD			4
#define GPIO5_HTCATHENA_RESERVED		5
#define GPIO6_HTCATHENA_RESERVED		6
#define GPIO7_HTCATHENA_RESERVED		7
#define GPIO8_HTCATHENA_RESERVED		8
#define GPIO9_HTCATHENA_KEYB_BUTTON_IRQ		9
#define GPIO10_HTCATHENA_KEYBOARD_IO		10
#define GPIO11_HTCATHENA_DPR_IRQ_D		11
#define GPIO12_HTCATHENA_EPSON_INT		12
#define GPIO13_HTCATHENA_EP_INT			13
#define GPIO14_HTCATHENA_CPLD1_EXT_INT		14
#define GPIO15_HTCATHENA_CS1			15
#define GPIO16_HTCATHENA_PWM0_OUT_BLK		16
#define GPIO17_HTCATHENA_KEY_VOL_UP		17
#define GPIO18_HTCATHENA_RDY			18
#define GPIO19_HTCATHENA_DPR_IRQ_P9		19
#define GPIO20_HTCATHENA_DPR_IRQ_P3		20
#define GPIO21_HTCATHENA_ATI_SD_INT		21
#define GPIO22_HTCATHENA_DPR_P9			22
#define GPIO23_HTCATHENA_SSP1_CLK		23
#define GPIO24_HTCATHENA_SSP1_FRM		24
#define GPIO25_HTCATHENA_SSP1_TXD		25
#define GPIO26_HTCATHENA_SSP1_RXD		26
#define GPIO27_HTCATHENA_TS_PENDOWN		27
#define GPIO28_HTCATHENA_PLAYSOUND		28
#define GPIO29_HTCATHENA_SOUND			29
#define GPIO30_HTCATHENA_SOUND			30
#define GPIO31_HTCATHENA_EXT_IRQ		31
#define GPIO32_HTCATHENA_MM_CLK			32
#define GPIO33_HTCATHENA_CS5			33
#define GPIO34_HTCATHENA_FF_UART_RXD		34
#define GPIO35_HTCATHENA_WIFI_IRQ		35
#define GPIO36_HTCATHENA_SSP2_CLK		36
#define GPIO37_HTCATHENA_IRQ			37
#define GPIO38_HTCATHENA_SSP2_TXD		38
#define GPIO39_HTCATHENA_FF_UART_TXD		39
#define GPIO40_HTCATHENA_SSP2_RXD		40
#define GPIO41_HTCATHENA_DPR_P1			41
#define GPIO42_HTCATHENA_BT_UART_RXD		42
#define GPIO43_HTCATHENA_BT_UART_TXD		43
#define GPIO44_HTCATHENA_BT_UART_CTS		44
#define GPIO45_HTCATHENA_BT_UART_RTS		45
#define GPIO46_HTCATHENA_ST_UART_RXD		46
#define GPIO47_HTCATHENA_ST_UART_TXD		47
#define GPIO48_HTCATHENA_DPR_P2			48
#define GPIO49_HTCATHENA_PWE			49
#define GPIO50_HTCATHENA_DPR_RESET5		50
#define GPIO51_HTCATHENA_DPR_IRQ_AT		51
#define GPIO52_HTCATHENA_DPR_IRQ_P2		52
#define GPIO53_HTCATHENA_DPR_D			53
#define GPIO54_HTCATHENA_WIFI			54
#define GPIO55_HTCATHENA_DPR_IRQ_P1		55
#define GPIO56_HTCATHENA_GPS			56
#define GPIO57_HTCATHENA_SOUND			57
#define GPIO58_HTCATHENA_GPS			58
#define GPIO59_HTCATHENA_MISC			59
#define GPIO60_HTCATHENA_WIFI			60
#define GPIO61_HTCATHENA_GPS			61
#define GPIO62_HTCATHENA_LCD_POWER_11		62
#define GPIO63_HTCATHENA_LCD_POWER_1		63
#define GPIO64_HTCATHENA_LCD_POWER_21		64
#define GPIO65_HTCATHENA_LCD_POWER_2		65
#define GPIO66_HTCATHENA_SD_POWER		66
#define GPIO67_HTCATHENA_SOUND_RELATED		67
#define GPIO68_HTCATHENA_EPSON_POWER		68
#define GPIO69_HTCATHENA_KBD_POWER		69
#define GPIO70_HTCATHENA_FLASHLED		70
#define GPIO71_HTCATHENA_TBD			71
#define GPIO72_HTCATHENA_WIFI_RESET		72
#define GPIO73_HTCATHENA_CAMERA			73
#define GPIO74_HTCATHENA_TBD			74
#define GPIO75_HTCATHENA_TBD			75
#define GPIO76_HTCATHENA_TBD			76
#define GPIO77_HTCATHENA_TBD			77
#define GPIO78_HTCATHENA_CS2			78
#define GPIO79_HTCATHENA_CS3			79
#define GPIO80_HTCATHENA_CS4			80
#define GPIO81_HTCATHENA_LCD			81
#define GPIO82_HTCATHENA_TBD			82
#define GPIO83_HTCATHENA_TBD			83
#define GPIO84_HTCATHENA_CAM_LED		84
#define GPIO85_HTCATHENA_PHN_POWER		85
#define GPIO86_HTCATHENA_CAMERA			86
#define GPIO87_HTCATHENA_CAMERA_POWER		87
#define GPIO88_HTCATHENA_USB_HPWR1		88
#define GPIO89_HTCATHENA_USB_HPEN1		89
#define GPIO90_HTCATHENA_KEY_CALENDAR		90
#define GPIO91_HTCATHENA_TBD			91
#define GPIO92_HTCATHENA_MM_DAT_0		92
#define GPIO93_HTCATHENA_KEY_CAMERA		93
#define GPIO94_HTCATHENA_KEY_RECORD		94
#define GPIO95_HTCATHENA_KEY_WWW		95
#define GPIO96_HTCATHENA_TBD			96
#define GPIO97_HTCATHENA_TBD			97
#define GPIO98_HTCATHENA_KEY_SEND		98
#define GPIO99_HTCATHENA_KEY_END		99
#define GPIO100_HTCATHENA_TBD			100
#define GPIO101_HTCATHENA_BACKLIGHT		101
#define GPIO102_HTCATHENA_KEY_VOL_DOWN	102
#define GPIO103_HTCATHENA_KEY_RIGHT		103
#define GPIO104_HTCATHENA_KEY_UP		104
#define GPIO105_HTCATHENA_KEY_LEFT		105
#define GPIO106_HTCATHENA_KEY_DOWN		106
#define GPIO107_HTCATHENA_KEY_ENTER		107
#define GPIO108_HTCATHENA_TBD			108
#define GPIO109_HTCATHENA_MM_DAT_1		109
#define GPIO110_HTCATHENA_MM_DAT_2		110
#define GPIO111_HTCATHENA_MM_DAT_3		111
#define GPIO112_HTCATHENA_MM_CMD		112
#define GPIO113_HTCATHENA_TBD			113
#define GPIO114_HTCATHENA_TS_DAV		114
#define GPIO115_HTCATHENA_DREQ0			115
#define GPIO116_HTCATHENA_SD_DETECT		116
#define GPIO117_HTCATHENA_SCL			117
#define GPIO118_HTCATHENA_SDA			118
#define GPIO119_HTCATHENA_TBD			119



/*
 * CPLD EGPIOs
 */

/* CPLD 1 */



#define CPLD1_EGPIO(bank, bit) (CPLD1_EGPIO_BASE	+ 8*bank + bit)

/* ABCD Output */
/*	power related (orr)				 */
#define EGPIO1_A0_HTCATHENA_POWER_RELATED	CPLD1_EGPIO(0, 0)

#define EGPIO1_A1_HTCATHENA_TBD			CPLD1_EGPIO(0, 1)

#define EGPIO1_A2_HTCATHENA_TBD			CPLD1_EGPIO(0, 2)
/*	battery related (bic,orr) msleep10+spi		*/
#define EGPIO1_A3_HTCATHENA_BATTERY_RELATED	CPLD1_EGPIO(0, 3)
/*	bt pwr1 (on=1,reset=0,standby=1 ?)		*/
#define EGPIO1_A4_HTCATHENA_BT_PWR1		CPLD1_EGPIO(0, 4)
/*	bt pwr2 (on=1,off=0)				*/
#define EGPIO1_A5_HTCATHENA_BT_PWR2		CPLD1_EGPIO(0, 5)
/*	FIR pwr1 related				*/
#define EGPIO1_A6_HTCATHENA_FIR_PWR1_RELATED	CPLD1_EGPIO(0, 6)
/*	cam related(orr,bic) msleep10			*/
#define EGPIO1_A7_HTCATHENA_CAM_RELATED		CPLD1_EGPIO(0, 7)

/*	camera related (bic) sleep10			*/
#define EGPIO1_B0_HTCATHENA_CAM_RELATED		CPLD1_EGPIO(1, 0)
/*	phone power (on=1,off=0)			*/
#define EGPIO1_B1_HTCATHENA_PHONE_POWER		CPLD1_EGPIO(1, 1)
/*	phone reset (1,msleep 400,0)			*/
#define EGPIO1_B2_HTCATHENA_PHONE_RESET		CPLD1_EGPIO(1, 2)
/*	gsm led (on=1,off=0)				*/
#define EGPIO1_B3_HTCATHENA_GSM_LED		CPLD1_EGPIO(1, 3)
/*	gps led (on=1,off=0)				*/
#define EGPIO1_B4_HTCATHENA_GPS_LED		CPLD1_EGPIO(1, 4)
/*	alert led (on=1,off=0)				*/
#define EGPIO1_B5_HTCATHENA_ALERT_LED		CPLD1_EGPIO(1, 5)
/*	bt led (on=1,off=0)				 */
#define EGPIO1_B6_HTCATHENA_BT_LED		CPLD1_EGPIO(1, 6)
/*	wifi led (on=1,off=0)				*/
#define EGPIO1_B7_HTCATHENA_WIFI_LED		CPLD1_EGPIO(1, 7)


/*	charging led red=1				*/
#define EGPIO1_C0_HTCATHENA_CHARGING_LED_RED	CPLD1_EGPIO(2, 0)
/*	charging led green=1				*/
#define EGPIO1_C1_HTCATHENA_CHARGING_LED_GREEN	CPLD1_EGPIO(2, 1)
/*	charging led redblink=1				*/
#define EGPIO1_C2_HTCATHENA_CHARGING_LED_REDBLK	CPLD1_EGPIO(2, 2)
/*	wifi power (on=1,off=0)				*/
#define EGPIO1_C3_HTCATHENA_WIFI_POWER3		CPLD1_EGPIO(2, 3)
/*	epson power sleep 4b0				*/
#define EGPIO1_C4_HTCATHENA_EPSON_POWER_SLEEP	CPLD1_EGPIO(2, 4)

#define EGPIO1_C5_HTCATHENA_TBD			CPLD1_EGPIO(2, 5)
/*	wifi power (on=1,off=0)				*/
#define EGPIO1_C6_HTCATHENA_WIFI_POWER4		CPLD1_EGPIO(2, 6)
/*	USB_PUEN?					*/
#define EGPIO1_C7_HTCATHENA_USB_PUEN		CPLD1_EGPIO(2, 7)

/*	GPS power (=0 ?)				*/
#define EGPIO1_D0_HTCATHENA_GPS_POWER		CPLD1_EGPIO(3, 0)
/*	reset device (=1)				*/
#define EGPIO1_D1_HTCATHENA_RESET_DEVICE	CPLD1_EGPIO(3, 1)
/*	LCD panel bit2 (get				 */
#define EGPIO1_D2_HTCATHENA_LCD_PANEL_BIT2	CPLD1_EGPIO(3, 2)
/*	power related (get+bic,orr)			 */
#define EGPIO1_D3_HTCATHENA_POWER_RELATED	CPLD1_EGPIO(3, 3)
/*	LCD panel bit4 (get)				*/
#define EGPIO1_D4_HTCATHENA_LCD_PANEL_BIT4	CPLD1_EGPIO(3, 4)
/*	PXAUSBH related (was FIR pwr2)			*/
#define EGPIO1_D5_HTCATHENA_PXAUSBH_RELATED	CPLD1_EGPIO(3, 5)
/*	SD power (on=1)					*/
#define EGPIO1_D6_HTCATHENA_SD_POWER		CPLD1_EGPIO(3, 6)
/*	lcd bkl related (on=1)				*/
#define EGPIO1_D7_HTCATHENA_LCD_BKL		CPLD1_EGPIO(3, 7)


/*
 * E - CPLD IRQs
 */

#define ATHENA_IRQ(x)	(IRQ_BOARD_START + (x))
#define ATHENA_BT_WAKEUP_IRQ	ATHENA_IRQ(0)

#define ATHENA_HPEP_W_IRQ	ATHENA_IRQ(1) /*hpep (wired) irqack */
#define ATHENA_HPEXT_B_IRQ	ATHENA_IRQ(2) /* hpext (button)irqack*/
#define ATHENA_3_IRQ		ATHENA_IRQ(3) /* +irqack	*/
#define ATHENA_USB_CABLE_IRQ	ATHENA_IRQ(4) /* USB cable irqack*/
#define ATHENA_5_IRQ		ATHENA_IRQ(5) /* +irqack	*/
#define ATHENA_TV_OUT_IRQ	ATHENA_IRQ(6) /* 4-1 cable - TVout cable - irqack	*/
#define ATHENA_7_IRQ		ATHENA_IRQ(7) /* +irqack	*/
#define ATHENA_NR_IRQS	(IRQ_BOARD_START + 8)


/* FG input */

#define EGPIO1_F0_HTCATHENA_TBD			CPLD1_EGPIO(5, 0)
/*	misc (get)					*/
#define EGPIO1_F1_EXT_JACK				CPLD1_EGPIO(5, 1)

#define EGPIO1_F2_HP_EXT				CPLD1_EGPIO(5, 2)

#define EGPIO1_F3_HTCATHENA_TBD			CPLD1_EGPIO(5, 3)
/*	isp1582 related (get)				*/
#define EGPIO1_F4_HTCATHENA_USB20_CABLE_PLUGGED	CPLD1_EGPIO(5, 4)

#define EGPIO1_F5_HTCATHENA_TBD			CPLD1_EGPIO(5, 5)
/*	isp1582 related	(get)				*/
#define EGPIO1_F6_HTCATHENA_ISP1582_RELATED	CPLD1_EGPIO(5, 6)
/*	TVout cable inserted  (get)   inserted=0, removed=1	 */
#define EGPIO1_F7_HTCATHENA_TV_OUT	CPLD1_EGPIO(5, 7)

/*	battery related (get)				*/
#define EGPIO1_G0_HTCATHENA_BATTERY		CPLD1_EGPIO(6, 0)

#define EGPIO1_G1_HTCATHENA_TBD			CPLD1_EGPIO(6, 1)

#define EGPIO1_G2_HTCATHENA_TBD			CPLD1_EGPIO(6, 2)

#define EGPIO1_G3_HTCATHENA_TBD			CPLD1_EGPIO(6, 3)

#define EGPIO1_G4_HTCATHENA_TBD			CPLD1_EGPIO(6, 4)
/*	ISP related					 */
#define EGPIO1_G5_HTCATHENA_ISP1582_CPLD2	CPLD1_EGPIO(6, 5)

#define EGPIO1_G6_HTCATHENA_TBD			CPLD1_EGPIO(6, 6)

#define EGPIO1_G7_HTCATHENA_TBD			CPLD1_EGPIO(6, 7)

//  register n°7 not found

/* H Output */

#define EGPIO1_H0_HTCATHENA_TBD			CPLD1_EGPIO(8, 0)

#define EGPIO1_H1_HTCATHENA_TBD			CPLD1_EGPIO(8, 1)
/*	battery related (bic,orr)/ ATI reset?		*/
#define EGPIO1_H2_HTCATHENA_BATTERY_ATI		CPLD1_EGPIO(8, 2)
/*	TVout mode reset( =0,msleep 10, =1, msleep 10)	*/
#define EGPIO1_H3_HTCATHENA_TV_OUT_RESET	CPLD1_EGPIO(8, 3)
/*	ISP related					 */
#define EGPIO1_H4_HTCATHENA_ISP1582_CS	CPLD1_EGPIO(8, 4)
	/*	ISP related	 */			
#define EGPIO1_H5_HTCATHENA_ISP1582_CS	CPLD1_EGPIO(8, 5)

#define EGPIO1_H6_HTCATHENA_TBD			CPLD1_EGPIO(8, 6)

#define EGPIO1_H7_HTCATHENA_TBD			 CPLD1_EGPIO(8, 7)



/* CPLD 2 */


/* Output */

/*	LCD pwr (on=1)					*/
#define EGPIO2_HTCATHENA_LCD_POWER		CPLD2_EGPIO_BASE
/*	LCD pwr (on=1, off=0)				*/
#define EGPIO2_HTCATHENA_ATI_RESET		(CPLD2_EGPIO_BASE+1)
/*	i2c (on=1)					*/
#define EGPIO2_HTCATHENA_I2C1			(CPLD2_EGPIO_BASE+2)
/*	i2c (on=1)					*/
#define EGPIO2_HTCATHENA_I2C2			(CPLD2_EGPIO_BASE+3)
/*	i2c (on=1)					*/
#define EGPIO2_HTCATHENA_I2C3			(CPLD2_EGPIO_BASE+4)
/*	backlight pwr (on=1)				*/
#define EGPIO2_HTCATHENA_BKL_POWER		(CPLD2_EGPIO_BASE+5)
/*	wifi power (on=1,off=0)				*/
#define EGPIO2_HTCATHENA_WIFI_POWER1		(CPLD2_EGPIO_BASE+6)
/*	wifi power (on=1,off=0)				*/
#define EGPIO2_HTCATHENA_WIFI_POWER2		(CPLD2_EGPIO_BASE+7)
/*	wifi power (on=1,off=0				*/
#define EGPIO2_HTCATHENA_TV_OUT_INIT		(CPLD2_EGPIO_BASE+8)

/* Input */

/*	BOARDID0					*/
#define EGPIO2_HTCATHENA_BOARDID0		(CPLD2_EGPIO_BASE+13)
/*	BOARDID1					*/
#define EGPIO2_HTCATHENA_BOARDID1		(CPLD2_EGPIO_BASE+14)
/*	BOARDID2					*/
#define EGPIO2_HTCATHENA_BOARDID2		(CPLD2_EGPIO_BASE+15)
 
	

#endif /* _HTCATHENA_H_ */
